name: Build Release IOS

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:

  build:
    name: build release
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: macos-latest-nightly

    - name: Install Rust
      run: |
        rustup install stable
        rustup default nightly
        rustup target add aarch64-apple-ios x86_64-apple-ios
        rustup show
        cargo install cargo-lipo

    - name: Build
      run: | 
        cargo lipo --release --targets aarch64-apple-ios x86_64-apple-ios
        cbindgen ./api/src/lib.rs -l c > ${{github.workspace}}/target/connector.h
        
        LIBS=./mobile-sdk/imKeyCoreX/imKeyCoreX
        cp ./target/universal/release/libconnector.a $LIBS/libconnector.a
        cp ./target/connector.h $LIBS/connector.h
        if [ -d "./ios-release" ]; then
          rm -rf ./ios-release
        fi
        
        pushd ./mobile-sdk/imKeyCoreX
        BUILD_DIR=./Products
        BUILD_ROOT=./Products
        SYMROOT=./Products
        BUILD_PRODUCTS=./Products
        CONFIGURATION=Release
        PROJECT_NAME=imKeyCoreX
        
        mkdir -p $BUILD_DIR
        UNIVERSAL_OUTPUTFOLDER=$BUILD_DIR/$CONFIGURATION-Universal
        mkdir -p $UNIVERSAL_OUTPUTFOLDER
 
        xcodebuild -target $PROJECT_NAME ONLY_ACTIVE_ARCH=NO -configuration $CONFIGURATION -sdk iphoneos BUILD_DIR=$BUILD_DIR BUILD_ROOT=$BUILD_ROOT build
        xcodebuild -target $PROJECT_NAME -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR=$BUILD_DIR BUILD_ROOT=$BUILD_ROOT EXCLUDED_ARCHS=arm64 build
        
        cp -R $BUILD_DIR/$CONFIGURATION-iphoneos/$PROJECT_NAME.framework $UNIVERSAL_OUTPUTFOLDER/
        
        lipo -create -output $UNIVERSAL_OUTPUTFOLDER/$PROJECT_NAME.framework/$PROJECT_NAME $BUILD_PRODUCTS/Debug-iphonesimulator/$PROJECT_NAME.framework/$PROJECT_NAME $BUILD_DIR/$CONFIGURATION-iphoneos/$PROJECT_NAME.framework/$PROJECT_NAME
        
        cp -R $UNIVERSAL_OUTPUTFOLDER/ ../../ios-release
        rm -rf $UNIVERSAL_OUTPUTFOLDER 
        popd
        
    - name: Publish To Nuexs
      run: |
        pushd ./ios-release
        PACKAGE_NAME=ios-release-test1.zip
        zip -q -r $PACKAGE_NAME .
        ls
        curl -v -u xuyunzhao:${{secrets.NEXUS_PASSWORD}} --upload-file $PACKAGE_NAME https://nexus.token.im/repository/im-releases/im/imkey/ios/test1/$PACKAGE_NAME
        popd
        
      
      
      
